# Generated by Django 3.1.7 on 2021-03-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0002_auto_20210308_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
